basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name="basket_summary"),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update')
]

pay/urls.py
from django.urls import path

from . import views

app_name = 'pay'

urlpatterns = [
    path('', views.index, name='basket'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/store/products/category.html
{% extends '../base.html' %}
{% load static %}
{% block title %}{{ category.name|title }}{% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="pb-3 h5">{{ category.name|title }}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
           <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                  <a class="text-dark text-decoration-none" ><h3>{{ product.title }}</h3></a><br>
                  <a class="text-dark text-decoration-none" >Rs. {{ product.price }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ product.get_absolute_url }}">View</a></button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="md-0 h4">{{ product.title }}</h1>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="col border-bottom">
                    <div class="row p-3">
                        <div class="col-6">Cost</div>
                        <div class="col-6 text-end"><span class="h4 fw-bold">Rs. {{ product.price }}</span></div>
                    </div>
                </div>
                <div class="col">
                    <div class="row p-3">
                        <div class="col-6">
                            <label for="select">Qty</label>
                            <select id="select">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                        <div class="col-6 text-end">
                            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to Basket</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>
</div>


<script>
    $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url "basket:basket_add" %}',
    data: {
    productid: $('#add-button').val(),
    productqty: $('#select option:selected').text(),
    csrfmiddlewaretoken: "{{csrf_token}}",
    action: 'post'
    },
    success: function (json){
    document.getElementById("basket-qty").innerHTML = json.qty
    },
    error: function(xhr, errmsg, err){}
    });
    })
</script>
{% endblock %}